---
- name: Tune oVirt engine with engine-config, version specific
  shell: "engine-config -s {{ item.key }}='{{ item.value }}' --cver={{ item.version }}"
  with_items: "{{ ovirt_engine_config | list }}"
  when: ovirt_engine_config is defined and item.version != "general"

- name: Tune oVirt engine with engine-config, regardless version
  shell: "engine-config -s {{ item.key }}='{{ item.value }}'"
  with_items: "{{ ovirt_engine_config | list }}"
  when: ovirt_engine_config is defined and item.version == "general"

- name: Copy property file to engine
  copy:
    content: "{{ ovirt_engine_config_property_file }}"
    dest: "/tmp/ovirt_engine_config.properties"
  when: ovirt_engine_config_property_file is defined

- name: Tune oVirt engine with engine-config; from property file
  shell: "engine-config --properties=/tmp/ovirt_engine_config.properties"
  when: ovirt_engine_config_property_file is defined

# oVirt engine restart is required
- name: restart of ovirt-engine service
  service:
    name: ovirt-engine
    state: restarted

- name: check health status of page
  uri:
    url: "http://localhost/ovirt-engine/services/health"
    status_code: 200
  register: health_page
  retries: 12
  delay: 10
  until: health_page|success
