---
galaxy_info:
  author: "Lukas Bednar"
  description: "Collects logs from oVirt deployment"
  company: "Red Hat"
  license: "GPLv3"
  min_ansible_version: 1.9
  platforms:
    - name: EL
      versions:
        - all
  galaxy_tags:
    - installer
